---
- name: Install alacritty
  ansible.builtin.include_role:
    name: jahrik.alacritty

- name: Install and configure zsh
  ansible.builtin.include_role:
    name: jahrik.zsh

- name: Install nvim, lazy, lsp, and plugins
  ansible.builtin.include_role:
    name: jahrik.nvim
