---
- name: Install alacritty
  ansible.builtin.include_role:
    name: jahrik.alacritty

- name: Install and configure zsh
  ansible.builtin.include_role:
    name: jahrik.zsh

- name: Install nvim, lazy, lsp, and plugins
  ansible.builtin.include_role:
    name: jahrik.nvim

- name: Configure Konsole
  ansible.builtin.include_tasks: konsole.yml

- name: Install extra CLI tools
  ansible.builtin.include_tasks: tools.yml

- name: Setup Docker/dind
  ansible.builtin.include_tasks: docker.yml

- name: Configure KDE Plasma
  ansible.builtin.include_tasks: kde.yml
