---
- name: Rebuild KDE system configuration cache
  ansible.builtin.command: kbuildsycoca6 --noincremental
  changed_when: false
  failed_when: false
  when: ansible_distribution_release == 'holo'

- name: Restart plasmashell
  ansible.builtin.systemd:
    name: plasma-plasmashell.service
    scope: user
    state: restarted
  changed_when: false
  failed_when: false
  when: ansible_distribution_release == 'holo'

- name: Rebuild bat theme cache
  ansible.builtin.command:
    cmd: "{{ ansible_user_dir }}/.local/bin/bat cache --build"
  changed_when: true

- name: Reconfigure KWin
  ansible.builtin.command:
    cmd: qdbus org.kde.KWin /KWin reconfigure
  changed_when: false
  failed_when: false
  when: ansible_distribution_release == 'holo'
