---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: steamdeck
    image: jahrik/docker-archlinux-ansible
    pre_build_image: true
    pull: true
    privileged: true
    security_opts:
      - seccomp=unconfined
provisioner:
  name: ansible
verifier:
  name: ansible
