---
dependency:
  name: galaxy
driver:
  name: default
platforms:
  - name: localhost
provisioner:
  name: ansible
  inventory:
    hosts:
      all:
        vars:
          dind_host: tcp://127.0.0.1:2375
          distrobox_dev_name: dev
          pianobar_box_name: pianobar
    host_vars:
      localhost:
        ansible_connection: local
        ansible_python_interpreter: "{{ ansible_playbook_python }}"
verifier:
  name: ansible
